import type { AnySchema } from 'ajv';

export const generatedSpringProjectSchema: AnySchema = {
  $schema: 'https://json-schema.org/draft/2020-12/schema',
  $id: 'https://uml-class-designer.local/contracts/generated-spring-project/0.1.0',
  title: 'UML Class Designer generated Spring Boot project',
  description: 'Deterministic in-memory Spring Boot project generated from a relational model.',
  type: 'object',
  additionalProperties: false,
  required: ['generatorVersion', 'sourceSchemaVersion', 'metadata', 'files', 'diagnostics'],
  properties: {
    generatorVersion: { const: '0.1.0' },
    sourceSchemaVersion: { const: '0.1.0' },
    metadata: { $ref: '#/$defs/metadata' },
    files: { type: 'array', minItems: 1, items: { $ref: '#/$defs/file' } },
    diagnostics: { type: 'array', items: { $ref: '#/$defs/diagnostic' } },
  },
  $defs: {
    nonBlank: { type: 'string', minLength: 1, maxLength: 240 },
    file: {
      type: 'object',
      additionalProperties: false,
      required: ['path', 'content', 'byteLength', 'sha256'],
      properties: {
        path: {
          type: 'string',
          minLength: 1,
          maxLength: 500,
          pattern: '^(?!/)(?!.*\\\\)(?!.*(?:^|/)\\.\\.(?:/|$))(?!.*//).+$',
        },
        content: { type: 'string' },
        byteLength: { type: 'integer', minimum: 0 },
        sha256: { type: 'string', pattern: '^[a-f0-9]{64}$' },
      },
    },
    diagnostic: {
      type: 'object',
      additionalProperties: false,
      required: ['severity', 'code', 'message'],
      properties: {
        severity: { enum: ['ERROR', 'WARNING', 'INFO'] },
        code: { type: 'string', pattern: '^[A-Z][A-Z0-9_]{1,79}$' },
        message: { $ref: '#/$defs/nonBlank' },
        path: { type: 'string', minLength: 1, maxLength: 240 },
        sourceIds: {
          type: 'array',
          minItems: 1,
          uniqueItems: true,
          items: { type: 'string', minLength: 1, maxLength: 160 },
        },
      },
    },
    metadata: {
      type: 'object',
      additionalProperties: false,
      required: [
        'relationalSchemaVersion',
        'projectId',
        'projectName',
        'groupId',
        'artifactId',
        'packageName',
        'applicationName',
        'versions',
      ],
      properties: {
        relationalSchemaVersion: { const: '0.1.0' },
        projectId: { $ref: '#/$defs/nonBlank' },
        projectName: { $ref: '#/$defs/nonBlank' },
        groupId: { type: 'string', pattern: '^[a-z][a-z0-9]*(?:\\.[a-z][a-z0-9]*)*$' },
        artifactId: { type: 'string', pattern: '^[a-z][a-z0-9.-]{0,99}$' },
        packageName: { type: 'string', pattern: '^[a-z][a-z0-9]*(?:\\.[a-z][a-z0-9]*)*$' },
        applicationName: { type: 'string', pattern: '^[A-Z][A-Za-z0-9_$]*$' },
        versions: { $ref: '#/$defs/versions' },
      },
    },
    versions: {
      type: 'object',
      additionalProperties: false,
      required: ['java', 'springBoot', 'springDataJpa', 'flyway', 'mavenCompilerPlugin'],
      properties: {
        java: { const: '21' },
        springBoot: { const: '4.1.1' },
        springDataJpa: { const: 'managed-by-spring-boot' },
        flyway: { const: '12.4.0' },
        mavenCompilerPlugin: { const: 'managed-by-spring-boot-parent' },
      },
    },
  },
};
